### ISSUE TITLE
Dockerize this app

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/voting-app#1]

**Comment by felipecaputo** [comment]
I'll make this later today o/

You will add this to some CI tool to auto publish the image?

**Comment by ElenaMLopez** [comment]
this look nice! I try to learn how hehehe. TX!

**Comment by dfirebaugh** [comment]
Yes, I'd like to do something with travisCI and auto publish to something like google cloud engine or similar

thanks,
DF

**Comment by felipecaputo** [comment]
I will help you with both if you'ld like. As soon as I get home today.

I work with gitlab-ci here at work, but I also have some project with travis, you just need to get an account on travis and get your dockerhub auth token configured inside your travis account to enable this
